#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Iñaki Arango"
email = "arangoinaki@gmail.com"

[aliases]
spr = ["util", "exec", "--", "jj-spr"]

[remotes.origin]
auto-track-bookmarks = "*"

[revset-aliases]
# Prevent rewriting pushed commits
'immutable_heads()' = 'builtin_immutable_heads() | remote_bookmarks()'
# Shorthand for trunk
'trunk()' = 'main@origin'
